// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACollapse: typeof import('@arco-design/web-vue')['Collapse']
    ACollapseItem: typeof import('@arco-design/web-vue')['CollapseItem']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AInput: typeof import('@arco-design/web-vue')['Input']
    'AInput-': typeof import('@arco-design/web-vue')['Input-']
    AInputN: typeof import('@arco-design/web-vue')['InputN']
    AInputNu: typeof import('@arco-design/web-vue')['InputNu']
    AInputNum: typeof import('@arco-design/web-vue')['InputNum']
    AInputNumbe: typeof import('@arco-design/web-vue')['InputNumbe']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    AInputP: typeof import('@arco-design/web-vue')['InputP']
    AInputPa: typeof import('@arco-design/web-vue')['InputPa']
    AInputPas: typeof import('@arco-design/web-vue')['InputPas']
    AInputPass: typeof import('@arco-design/web-vue')['InputPass']
    AInputPassw: typeof import('@arco-design/web-vue')['InputPassw']
    AInputPasswo: typeof import('@arco-design/web-vue')['InputPasswo']
    AInputPasswor: typeof import('@arco-design/web-vue')['InputPasswor']
    AInputPassword: typeof import('@arco-design/web-vue')['InputPassword']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    ALayoutSider: typeof import('@arco-design/web-vue')['LayoutSider']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    AProgress: typeof import('@arco-design/web-vue')['Progress']
    AResult: typeof import('@arco-design/web-vue')['Result']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATabPane: typeof import('@arco-design/web-vue')['TabPane']
    ATabs: typeof import('@arco-design/web-vue')['Tabs']
    ATypography: typeof import('@arco-design/web-vue')['Typography']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    ChangeUsername: typeof import('./src/components/ChangeUsername.vue')['default']
    GeneralSettings: typeof import('./src/components/GeneralSettings.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserManager: typeof import('./src/components/UserManager.vue')['default']
  }
}
