// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Caddy: typeof import('./src/components/caddy.vue')['default']
    Codemirror: typeof import('./src/components/codemirror.vue')['default']
    Docker: typeof import('./src/components/docker.vue')['default']
    Docker_status: typeof import('./src/components/docker_status.vue')['default']
    Ftp: typeof import('./src/components/ftp.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Home: typeof import('./src/components/home.vue')['default']
    Login: typeof import('./src/components/login.vue')['default']
    Nvpress: typeof import('./src/components/nvpress.vue')['default']
    Nvpress_error: typeof import('./src/components/nvpress_error.vue')['default']
    Restart_docker_service: typeof import('./src/components/restart_docker_service.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
